version: '3.7'

services:
  postgres:
    image: library/postgres:14
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
      - POSTGRES_PORT=5432
    volumes:
      - $HOME/PycharmProjects/GitHub/.db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - main

  redis:
    image: library/redis:latest
    container_name: redis-cache
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    depends_on:
      - postgres
    networks:
      - main

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_data:/vol/web
    depends_on:
      - postgres
      - redis
    networks:
      - main

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - main
    links:
      - web

  worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_data:/vol/web
      - $HOME/PycharmProjects/GitHub/.rediska:/app/tapp/rediska
    command: [ 'celery', '-A', 'tapp', 'worker', '-B', '-l', 'info']
    depends_on:
      - web
    links:
      - web
      - nginx
    networks:
      - main


volumes:
  static_data:
  .rediska:

networks:
  main: